import re

class SQLQueryCleaner:
    """
    Cleans and sanitizes SQL queries generated by LLM.
    """
    
    def __init__(self, max_limit: int = 10000):
        self.max_limit = max_limit
        self.allowed_tables = ['work_orders']
        self.allowed_columns = [
            'work_order_id', 'service_provider', 'status', 'priority',
            'city', 'region', 'order_type', 'customer_type', 'cost_inr',
            'resolution_time_hrs', 'sla_met', 'customer_rating',
            'escalation_count', 'created_date', 'completed_date'
        ]
    
    def clean(self, sql: str) -> str:
        """Clean and sanitize SQL query."""
        if not sql:
            return ""
            
        # Remove markdown code blocks if present
        sql = re.sub(r'```sql\s*', '', sql, flags=re.IGNORECASE)
        sql = re.sub(r'```\s*', '', sql)
        
        # Remove comments
        sql = re.sub(r'--.*$', '', sql, flags=re.MULTILINE)
        sql = re.sub(r'/\*.*?\*/', '', sql, flags=re.DOTALL)
        
        # Normalize whitespace
        sql = ' '.join(sql.split())
        
        # Basic fixes
        sql = sql.replace(' FROM orders', ' FROM work_orders')
        sql = sql.replace(' FROM "orders"', ' FROM work_orders')
        sql = sql.replace(' FROM table_order', ' FROM work_orders')
        sql = sql.replace(' FROM table_orders', ' FROM work_orders')
        sql = sql.replace(' FROM "table_order"', ' FROM work_orders')
        sql = sql.replace(' FROM "table_orders"', ' FROM work_orders')
        sql = sql.replace(' JOIN table_order', ' JOIN work_orders')
        sql = sql.replace(' JOIN table_orders', ' JOIN work_orders')
        sql = sql.replace(' JOIN "table_order"', ' JOIN work_orders')
        sql = sql.replace(' JOIN "table_orders"', ' JOIN work_orders')
        
        # Ensure LIMIT
        if 'LIMIT' not in sql.upper() and 'SELECT' in sql.upper():
            sql = sql.rstrip(';') + f' LIMIT {self.max_limit}'
        
        return sql.strip()
